// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalAffairsManagementSystem.Models;

namespace PersonalAffairsManagementSystem.Migrations
{
    [DbContext(typeof(S_ConstantDbContext))]
    [Migration("20200209043117_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonalAffairsManagementSystem.Models.S_Constant", b =>
                {
                    b.Property<string>("CName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CDscp");

                    b.Property<string>("CValue");

                    b.HasKey("CName");

                    b.ToTable("s_Constants");
                });
#pragma warning restore 612, 618
        }
    }
}
